config/routes.rb
Rails.application.routes.draw do
    
  
  
	resources :denemes
  get 'home/index'
  get 'home/about'

  root'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/deneme.rb
class Deneme < ApplicationRecord
end

app/models/kullanıcı.rb
class Kullanıcı < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/denemes_controller.rb
class DenemesController < ApplicationController
  before_action :set_deneme, only: [:show, :edit, :update, :destroy]

  # GET /denemes
  # GET /denemes.json
  def index
    @denemes = Deneme.all
  end

  # GET /denemes/1
  # GET /denemes/1.json
  def show
  end

  # GET /denemes/new
  def new
    @deneme = Deneme.new
  end

  # GET /denemes/1/edit
  def edit
  end

  # POST /denemes
  # POST /denemes.json
  def create
    @deneme = Deneme.new(deneme_params)

    respond_to do |format|
      if @deneme.save
        format.html { redirect_to @deneme, notice: 'Deneme was successfully created.' }
        format.json { render :show, status: :created, location: @deneme }
      else
        format.html { render :new }
        format.json { render json: @deneme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /denemes/1
  # PATCH/PUT /denemes/1.json
  def update
    respond_to do |format|
      if @deneme.update(deneme_params)
        format.html { redirect_to @deneme, notice: 'Deneme was successfully updated.' }
        format.json { render :show, status: :ok, location: @deneme }
      else
        format.html { render :edit }
        format.json { render json: @deneme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /denemes/1
  # DELETE /denemes/1.json
  def destroy
    @deneme.destroy
    respond_to do |format|
      format.html { redirect_to denemes_url, notice: 'Deneme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deneme
      @deneme = Deneme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deneme_params
      params.require(:deneme).permit(:AD, :SOYAD, :YAS, :EMAİL, :ADRES)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/denemes_helper.rb
module DenemesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/denemes/_form.html.erb
<%= form_with(model: deneme) do |form| %>
  <% if deneme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deneme.errors.count, "error") %> prohibited this deneme from being saved:</h2>

      <ul>
        <% deneme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <% form.label :AD %>
    <%= form.text_field :AD, class:"form-control", placeholder:"ad" %>
  </div>

  <div class="field mb-3">
    <% form.label :SOYAD %>
    <%= form.text_field :SOYAD, class:"form-control", placeholder:"soyad" %>
  </div>

  <div class="field mb-3">
    <% form.label :YAS %>
    <%= form.number_field :YAS, class:"form-control", placeholder:"yas" %>
  </div>

  <div class="field mb-3">
    <% form.label :EMAİL %>
    <%= form.text_field :EMAİL, class:"form-control",placeholder:"email" %>
  </div>

  <div class="field mb-3">
    <% form.label :ADRES %>
    <%= form.text_area :ADRES , class:"form-control", placeholder:"adres" %>

  </div>
  <br/>

  <div class="actions">
    <%= form.submit class:'btn btn secondary' %>
  </div>
<% end %> 

app/views/denemes/edit.html.erb
<h1>Editing Deneme</h1>

<%= render 'form', deneme: @deneme %>

<%= link_to 'Show', @deneme %> |
<%= link_to 'Back', denemes_path %>

app/views/denemes/index.html.erb
<h1>Kayıt Tablosu</h1>
<br/>

<table class="table table-striped">
   <thead class="table-dark">
    <tr>
      <th>Ad</th>
      <th>Soyad</th>
      <th>Yas</th>
      <th>Email</th>
      <th>Adres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @denemes.each do |deneme| %>
      <tr>
        <td><%= deneme.AD %></td>
        <td><%= deneme.SOYAD %></td>
        <td><%= deneme.YAS %></td>
        <td><%= deneme.EMAİL %></td>
        <td><%= deneme.ADRES %></td>
        <td><%= link_to 'Show', deneme %></td>
        <td><%= link_to 'Edit', edit_deneme_path(deneme) %></td>
        <td><%= link_to 'Destroy', deneme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deneme', new_deneme_path, class:"btn btn-primary" %>

app/views/denemes/new.html.erb
<h1>Kayıt Oluştur</h1>
<br/>

<div class="alert alert-warning" role="alert">
  Tüm alanları doldurunuz!
</div>

<%= render 'form', deneme: @deneme %>


<%= link_to 'Back', denemes_path, class:"btn btn-dark" %>

app/views/denemes/show.html.erb
<p>
  <strong>Ad:</strong>
  <%= @deneme.AD %>
</p>

<p>
  <strong>Soyad:</strong>
  <%= @deneme.SOYAD %>
</p>

<p>
  <strong>Yas:</strong>
  <%= @deneme.YAS %>
</p>

<p>
  <strong>Emaİl:</strong>
  <%= @deneme.EMAİL %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @deneme.ADRES %>
</p>

<%= link_to 'Edit', edit_deneme_path(@deneme),class:"btn btn-primary" %>
<%= link_to 'Back', denemes_path,class:"btn btn-primary" %>
 

app/views/home/_baslik.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<%= link_to 'Weblog App', 
	root_path, class:"navbar-brand" %>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
        	<%= link_to "Hakkımızda", home_about_path, class:"navbar-link" %>
         
        </li> 
        <div class="container"> <div class="container">

        <li class="nav-item">
        	<%= link_to "Tablo", denemes_path, class:"navbar-link" %>
        </li>
        <div class="container"> <div class="container">

        <li class="nav-item">
        	<%= link_to "Kayıt", new_deneme_path, class:"navbar-link" %>
         
        </li> 
         <div class="container"> <div class="container">
        
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>vaka çalışması hakkında...</h1>

app/views/home/index.html.erb
<h1>VAKA ÇALIŞMASI</h1>
Basit bir vaka çalışması

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
	<%= notice %>
 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Weblogs App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>
  <body>
        
    <%= render 'home/baslik' %>
    <% if notice %>
      <%= render 'layouts/alerts' %>
      
      <% end %>    


    <div class="container"> <div class="container">
    

      
    <%= yield %>
  </div></div>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>